### PR TITLE
Update findslot.py

### PR DESCRIPTION
**Pull request by kaiwenShen**
this is also needed for my internet, which is fairly quick (30mps). it just needs some time to load.

### CODE REVIEW

**Comment by kcajc** [comment]
@kaiwenShen Thanks for the PR. Just curious as I'm not maintaining this one any more, does it still work?

**Comment by kaiwenShen** [comment]
@kcajc hi there, it worked for me so far, but likely because there is no slot currently available. will let you know if there is any changes required for this to work
ps: the latest interview slot currently is January 2026. ridiculous

**Comment by kcajc** [comment]
I've invited you to this repo, feel free to make more changes or update the docs. 

When this was first written in 2022 it did got me and a few of my friends slots within 1-3 months. But I think they changed the rules to ban repeatedly rescheduling? Anyway thanks again for maintaining this. Wish you the best of luck for your appointment.

**Comment by kaiwenShen** [comment]
thank you so much!

**Pull request merged**
