### PR TITLE
Add detector using gmail

### PR DESCRIPTION
**Pull request by jywyq**
The gmail part was copied from https://github.com/paulc/gmail-sender/tree/master 

This added a function to pull from the usvisa-canada website without trying to book the slot, but only send an email as notification

### CODE REVIEW

**Comment by kcajc** [comment]
Wow huge thanks for the PR! Looks like a really awesome feature! 

@jywyq The code looks pretty neat to me. My only concern is if this is tested?

**Comment by jywyq** [comment]
Yep it's tested. You can test it pretty easily by pulling it locally. It doesn't require you to pay the visa application fee to get to this page.

**Comment by jywyq** [comment]
Oh btw it does require you to register an account and filling your visa type information

**Review by kcajc — APPROVED** [review]
Looks good to me, I'll make a few minor changes to the README after it's merged.

**Pull request merged**
